export { default as Dashboard } from "./dashboard/Dashboard"
export { default as Home } from "./home/Home"
export {default as Contact } from "./contact/Contact"
export {default as About} from "./about/About"
export {default as Services} from "./services/Services"